### ISSUE TITLE
Fix font part

### ISSUE THREAD

**Issue by hallucino** [Gigoteur/PX8#24]
I need to improve few things:

- [x] fix non valid characters in the current font
- [ ] add a way to change the font dynamically

**Comment by hallucino** [comment]
@johnbatty it seems ok for all characters no ?

**Comment by johnbatty** [comment]
Yes, I think the current font is now good!
I also want to add one or more bigger font(s) for higher resolution modes, and then also obviously need to provide a way of selecting them.
I think I might change the font definition format to store the glyphs in row by row format rather than the current column by column format.  Will make them easier to define.  Do you have any objection to that?  I'd obviously fix up the font drawing code too!

**Comment by hallucino** [comment]
no objection, it seems a good idea !

**Comment by hallucino** [comment]
Seems ok no ? We could close this bug ?

**Comment by johnbatty** [comment]
Yep, I agree!
